/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'lightly_active' : null } |
  { 'sedentary' : null } |
  { 'extra_active' : null } |
  { 'very_active' : null } |
  { 'moderately_active' : null };
export interface AdminReport {
  'id' : string,
  'goal' : string,
  'name' : string,
  'whatsapp' : string,
  'referredBy' : string,
  'rewardPaid' : boolean,
  'amount' : number,
  'paidAt' : string,
}
export interface DayPlan {
  'breakfast' : Meal,
  'lunch' : Meal,
  'snacks' : Array<Meal>,
  'dinner' : Meal,
}
export interface DietPlan {
  'bmr' : number,
  'daily_calories' : number,
  'tdee' : number,
  'hydration_recommendation' : number,
  'macros' : MacronutrientBreakdown,
  'health_tips' : Array<string>,
  'weekly_plan' : Array<DayPlan>,
  'profile_id' : string,
}
export interface DietProfile {
  'id' : string,
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'supplements' : Array<string>,
  'meals_per_day' : bigint,
  'sleep_hours' : number,
  'health_conditions' : Array<string>,
  'goal' : HealthGoal,
  'water_intake' : number,
  'name' : string,
  'dietary_preferences' : Array<string>,
  'activity_level' : ActivityLevel,
  'stress_level' : StressLevel,
  'gender' : Gender,
  'food_allergies' : Array<string>,
}
export type Gender = { 'female' : null } |
  { 'male' : null };
export type HealthGoal = { 'body_recomposition' : null } |
  { 'muscle_gain' : null } |
  { 'weight_loss' : null } |
  { 'maintenance' : null };
export interface MacronutrientBreakdown {
  'carbs' : number,
  'fats' : number,
  'protein' : number,
}
export interface Meal {
  'carbs' : number,
  'fats' : number,
  'calories' : number,
  'name' : string,
  'ingredients' : Array<string>,
  'protein' : number,
}
export type StressLevel = { 'low' : null } |
  { 'high' : null } |
  { 'very_high' : null } |
  { 'moderate' : null };
export interface _SERVICE {
  /**
   * / * Admin Report Methods **
   * / Add admin report. Public, no authentication performed!
   */
  'addAdminReport' : ActorMethod<[AdminReport], undefined>,
  'addDietPlan' : ActorMethod<[DietPlan], undefined>,
  /**
   * / * DietPlan Methods **
   */
  'addProfile' : ActorMethod<[DietProfile], undefined>,
  'deleteWrapper' : ActorMethod<[string], string>,
  /**
   * / Get all admin reports. Public, no authentication performed!
   */
  'getAdminReports' : ActorMethod<[], Array<AdminReport>>,
  'getAllDietPlans' : ActorMethod<[], Array<DietPlan>>,
  'getAllProfiles' : ActorMethod<[], Array<DietProfile>>,
  'getDietPlan' : ActorMethod<[string], DietPlan>,
  'getProfile' : ActorMethod<[string], DietProfile>,
  /**
   * / Set rewardPaid flag to true. Public, no authentication performed!
   */
  'markRewardPaid' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];