/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminReport = IDL.Record({
  'id' : IDL.Text,
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'referredBy' : IDL.Text,
  'rewardPaid' : IDL.Bool,
  'amount' : IDL.Float64,
  'paidAt' : IDL.Text,
});
export const MacronutrientBreakdown = IDL.Record({
  'carbs' : IDL.Float64,
  'fats' : IDL.Float64,
  'protein' : IDL.Float64,
});
export const Meal = IDL.Record({
  'carbs' : IDL.Float64,
  'fats' : IDL.Float64,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
  'protein' : IDL.Float64,
});
export const DayPlan = IDL.Record({
  'breakfast' : Meal,
  'lunch' : Meal,
  'snacks' : IDL.Vec(Meal),
  'dinner' : Meal,
});
export const DietPlan = IDL.Record({
  'bmr' : IDL.Float64,
  'daily_calories' : IDL.Float64,
  'tdee' : IDL.Float64,
  'hydration_recommendation' : IDL.Float64,
  'macros' : MacronutrientBreakdown,
  'health_tips' : IDL.Vec(IDL.Text),
  'weekly_plan' : IDL.Vec(DayPlan),
  'profile_id' : IDL.Text,
});
export const HealthGoal = IDL.Variant({
  'body_recomposition' : IDL.Null,
  'muscle_gain' : IDL.Null,
  'weight_loss' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const ActivityLevel = IDL.Variant({
  'lightly_active' : IDL.Null,
  'sedentary' : IDL.Null,
  'extra_active' : IDL.Null,
  'very_active' : IDL.Null,
  'moderately_active' : IDL.Null,
});
export const StressLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'very_high' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const DietProfile = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'supplements' : IDL.Vec(IDL.Text),
  'meals_per_day' : IDL.Nat,
  'sleep_hours' : IDL.Float64,
  'health_conditions' : IDL.Vec(IDL.Text),
  'goal' : HealthGoal,
  'water_intake' : IDL.Float64,
  'name' : IDL.Text,
  'dietary_preferences' : IDL.Vec(IDL.Text),
  'activity_level' : ActivityLevel,
  'stress_level' : StressLevel,
  'gender' : Gender,
  'food_allergies' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addAdminReport' : IDL.Func([AdminReport], [], []),
  'addDietPlan' : IDL.Func([DietPlan], [], []),
  'addProfile' : IDL.Func([DietProfile], [], []),
  'deleteWrapper' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAdminReports' : IDL.Func([], [IDL.Vec(AdminReport)], ['query']),
  'getAllDietPlans' : IDL.Func([], [IDL.Vec(DietPlan)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(DietProfile)], ['query']),
  'getDietPlan' : IDL.Func([IDL.Text], [DietPlan], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [DietProfile], ['query']),
  'markRewardPaid' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminReport = IDL.Record({
    'id' : IDL.Text,
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'referredBy' : IDL.Text,
    'rewardPaid' : IDL.Bool,
    'amount' : IDL.Float64,
    'paidAt' : IDL.Text,
  });
  const MacronutrientBreakdown = IDL.Record({
    'carbs' : IDL.Float64,
    'fats' : IDL.Float64,
    'protein' : IDL.Float64,
  });
  const Meal = IDL.Record({
    'carbs' : IDL.Float64,
    'fats' : IDL.Float64,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
    'protein' : IDL.Float64,
  });
  const DayPlan = IDL.Record({
    'breakfast' : Meal,
    'lunch' : Meal,
    'snacks' : IDL.Vec(Meal),
    'dinner' : Meal,
  });
  const DietPlan = IDL.Record({
    'bmr' : IDL.Float64,
    'daily_calories' : IDL.Float64,
    'tdee' : IDL.Float64,
    'hydration_recommendation' : IDL.Float64,
    'macros' : MacronutrientBreakdown,
    'health_tips' : IDL.Vec(IDL.Text),
    'weekly_plan' : IDL.Vec(DayPlan),
    'profile_id' : IDL.Text,
  });
  const HealthGoal = IDL.Variant({
    'body_recomposition' : IDL.Null,
    'muscle_gain' : IDL.Null,
    'weight_loss' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const ActivityLevel = IDL.Variant({
    'lightly_active' : IDL.Null,
    'sedentary' : IDL.Null,
    'extra_active' : IDL.Null,
    'very_active' : IDL.Null,
    'moderately_active' : IDL.Null,
  });
  const StressLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'very_high' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const DietProfile = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'supplements' : IDL.Vec(IDL.Text),
    'meals_per_day' : IDL.Nat,
    'sleep_hours' : IDL.Float64,
    'health_conditions' : IDL.Vec(IDL.Text),
    'goal' : HealthGoal,
    'water_intake' : IDL.Float64,
    'name' : IDL.Text,
    'dietary_preferences' : IDL.Vec(IDL.Text),
    'activity_level' : ActivityLevel,
    'stress_level' : StressLevel,
    'gender' : Gender,
    'food_allergies' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addAdminReport' : IDL.Func([AdminReport], [], []),
    'addDietPlan' : IDL.Func([DietPlan], [], []),
    'addProfile' : IDL.Func([DietProfile], [], []),
    'deleteWrapper' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAdminReports' : IDL.Func([], [IDL.Vec(AdminReport)], ['query']),
    'getAllDietPlans' : IDL.Func([], [IDL.Vec(DietPlan)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(DietProfile)], ['query']),
    'getDietPlan' : IDL.Func([IDL.Text], [DietPlan], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [DietProfile], ['query']),
    'markRewardPaid' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };