/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    carbs: number;
    fats: number;
    calories: number;
    name: string;
    ingredients: Array<string>;
    protein: number;
}
export interface AdminReport {
    id: string;
    goal: string;
    name: string;
    whatsapp: string;
    referredBy: string;
    rewardPaid: boolean;
    amount: number;
    paidAt: string;
}
export interface MacronutrientBreakdown {
    carbs: number;
    fats: number;
    protein: number;
}
export interface DietPlan {
    bmr: number;
    daily_calories: number;
    tdee: number;
    hydration_recommendation: number;
    macros: MacronutrientBreakdown;
    health_tips: Array<string>;
    weekly_plan: Array<DayPlan>;
    profile_id: string;
}
export interface DietProfile {
    id: string;
    age: bigint;
    weight: number;
    height: number;
    supplements: Array<string>;
    meals_per_day: bigint;
    sleep_hours: number;
    health_conditions: Array<string>;
    goal: HealthGoal;
    water_intake: number;
    name: string;
    dietary_preferences: Array<string>;
    activity_level: ActivityLevel;
    stress_level: StressLevel;
    gender: Gender;
    food_allergies: Array<string>;
}
export interface DayPlan {
    breakfast: Meal;
    lunch: Meal;
    snacks: Array<Meal>;
    dinner: Meal;
}
export enum ActivityLevel {
    lightly_active = "lightly_active",
    sedentary = "sedentary",
    extra_active = "extra_active",
    very_active = "very_active",
    moderately_active = "moderately_active"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum HealthGoal {
    body_recomposition = "body_recomposition",
    muscle_gain = "muscle_gain",
    weight_loss = "weight_loss",
    maintenance = "maintenance"
}
export enum StressLevel {
    low = "low",
    high = "high",
    very_high = "very_high",
    moderate = "moderate"
}
export interface backendInterface {
    /**
     * / * Admin Report Methods **
     * / Add admin report. Public, no authentication performed!
     */
    addAdminReport(report: AdminReport): Promise<void>;
    addDietPlan(plan: DietPlan): Promise<void>;
    /**
     * / * DietPlan Methods **
     */
    addProfile(profile: DietProfile): Promise<void>;
    deleteWrapper(arg0: string): Promise<string>;
    /**
     * / Get all admin reports. Public, no authentication performed!
     */
    getAdminReports(): Promise<Array<AdminReport>>;
    getAllDietPlans(): Promise<Array<DietPlan>>;
    getAllProfiles(): Promise<Array<DietProfile>>;
    getDietPlan(profile_id: string): Promise<DietPlan>;
    getProfile(id: string): Promise<DietProfile>;
    /**
     * / Set rewardPaid flag to true. Public, no authentication performed!
     */
    markRewardPaid(id: string): Promise<boolean>;
}
import type { ActivityLevel as _ActivityLevel, DietProfile as _DietProfile, Gender as _Gender, HealthGoal as _HealthGoal, StressLevel as _StressLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdminReport(arg0: AdminReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminReport(arg0);
            return result;
        }
    }
    async addDietPlan(arg0: DietPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDietPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDietPlan(arg0);
            return result;
        }
    }
    async addProfile(arg0: DietProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProfile(to_candid_DietProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProfile(to_candid_DietProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteWrapper(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWrapper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWrapper(arg0);
            return result;
        }
    }
    async getAdminReports(): Promise<Array<AdminReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminReports();
            return result;
        }
    }
    async getAllDietPlans(): Promise<Array<DietPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDietPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDietPlans();
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<DietProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDietPlan(arg0: string): Promise<DietPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietPlan(arg0);
            return result;
        }
    }
    async getProfile(arg0: string): Promise<DietProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_DietProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_DietProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markRewardPaid(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markRewardPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRewardPaid(arg0);
            return result;
        }
    }
}
function from_candid_ActivityLevel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DietProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietProfile): DietProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_HealthGoal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthGoal): HealthGoal {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StressLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StressLevel): StressLevel {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    weight: number;
    height: number;
    supplements: Array<string>;
    meals_per_day: bigint;
    sleep_hours: number;
    health_conditions: Array<string>;
    goal: _HealthGoal;
    water_intake: number;
    name: string;
    dietary_preferences: Array<string>;
    activity_level: _ActivityLevel;
    stress_level: _StressLevel;
    gender: _Gender;
    food_allergies: Array<string>;
}): {
    id: string;
    age: bigint;
    weight: number;
    height: number;
    supplements: Array<string>;
    meals_per_day: bigint;
    sleep_hours: number;
    health_conditions: Array<string>;
    goal: HealthGoal;
    water_intake: number;
    name: string;
    dietary_preferences: Array<string>;
    activity_level: ActivityLevel;
    stress_level: StressLevel;
    gender: Gender;
    food_allergies: Array<string>;
} {
    return {
        id: value.id,
        age: value.age,
        weight: value.weight,
        height: value.height,
        supplements: value.supplements,
        meals_per_day: value.meals_per_day,
        sleep_hours: value.sleep_hours,
        health_conditions: value.health_conditions,
        goal: from_candid_HealthGoal_n14(_uploadFile, _downloadFile, value.goal),
        water_intake: value.water_intake,
        name: value.name,
        dietary_preferences: value.dietary_preferences,
        activity_level: from_candid_ActivityLevel_n16(_uploadFile, _downloadFile, value.activity_level),
        stress_level: from_candid_StressLevel_n18(_uploadFile, _downloadFile, value.stress_level),
        gender: from_candid_Gender_n20(_uploadFile, _downloadFile, value.gender),
        food_allergies: value.food_allergies
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    body_recomposition: null;
} | {
    muscle_gain: null;
} | {
    weight_loss: null;
} | {
    maintenance: null;
}): HealthGoal {
    return "body_recomposition" in value ? HealthGoal.body_recomposition : "muscle_gain" in value ? HealthGoal.muscle_gain : "weight_loss" in value ? HealthGoal.weight_loss : "maintenance" in value ? HealthGoal.maintenance : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lightly_active: null;
} | {
    sedentary: null;
} | {
    extra_active: null;
} | {
    very_active: null;
} | {
    moderately_active: null;
}): ActivityLevel {
    return "lightly_active" in value ? ActivityLevel.lightly_active : "sedentary" in value ? ActivityLevel.sedentary : "extra_active" in value ? ActivityLevel.extra_active : "very_active" in value ? ActivityLevel.very_active : "moderately_active" in value ? ActivityLevel.moderately_active : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    very_high: null;
} | {
    moderate: null;
}): StressLevel {
    return "low" in value ? StressLevel.low : "high" in value ? StressLevel.high : "very_high" in value ? StressLevel.very_high : "moderate" in value ? StressLevel.moderate : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietProfile>): Array<DietProfile> {
    return value.map((x)=>from_candid_DietProfile_n12(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_DietProfile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietProfile): _DietProfile {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_HealthGoal_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthGoal): _HealthGoal {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StressLevel_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StressLevel): _StressLevel {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    weight: number;
    height: number;
    supplements: Array<string>;
    meals_per_day: bigint;
    sleep_hours: number;
    health_conditions: Array<string>;
    goal: HealthGoal;
    water_intake: number;
    name: string;
    dietary_preferences: Array<string>;
    activity_level: ActivityLevel;
    stress_level: StressLevel;
    gender: Gender;
    food_allergies: Array<string>;
}): {
    id: string;
    age: bigint;
    weight: number;
    height: number;
    supplements: Array<string>;
    meals_per_day: bigint;
    sleep_hours: number;
    health_conditions: Array<string>;
    goal: _HealthGoal;
    water_intake: number;
    name: string;
    dietary_preferences: Array<string>;
    activity_level: _ActivityLevel;
    stress_level: _StressLevel;
    gender: _Gender;
    food_allergies: Array<string>;
} {
    return {
        id: value.id,
        age: value.age,
        weight: value.weight,
        height: value.height,
        supplements: value.supplements,
        meals_per_day: value.meals_per_day,
        sleep_hours: value.sleep_hours,
        health_conditions: value.health_conditions,
        goal: to_candid_HealthGoal_n3(_uploadFile, _downloadFile, value.goal),
        water_intake: value.water_intake,
        name: value.name,
        dietary_preferences: value.dietary_preferences,
        activity_level: to_candid_ActivityLevel_n5(_uploadFile, _downloadFile, value.activity_level),
        stress_level: to_candid_StressLevel_n7(_uploadFile, _downloadFile, value.stress_level),
        gender: to_candid_Gender_n9(_uploadFile, _downloadFile, value.gender),
        food_allergies: value.food_allergies
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthGoal): {
    body_recomposition: null;
} | {
    muscle_gain: null;
} | {
    weight_loss: null;
} | {
    maintenance: null;
} {
    return value == HealthGoal.body_recomposition ? {
        body_recomposition: null
    } : value == HealthGoal.muscle_gain ? {
        muscle_gain: null
    } : value == HealthGoal.weight_loss ? {
        weight_loss: null
    } : value == HealthGoal.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    lightly_active: null;
} | {
    sedentary: null;
} | {
    extra_active: null;
} | {
    very_active: null;
} | {
    moderately_active: null;
} {
    return value == ActivityLevel.lightly_active ? {
        lightly_active: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value == ActivityLevel.extra_active ? {
        extra_active: null
    } : value == ActivityLevel.very_active ? {
        very_active: null
    } : value == ActivityLevel.moderately_active ? {
        moderately_active: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StressLevel): {
    low: null;
} | {
    high: null;
} | {
    very_high: null;
} | {
    moderate: null;
} {
    return value == StressLevel.low ? {
        low: null
    } : value == StressLevel.high ? {
        high: null
    } : value == StressLevel.very_high ? {
        very_high: null
    } : value == StressLevel.moderate ? {
        moderate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
